UPDATE number_associations SET action = 'siedzi po turecku' WHERE number = 0 AND is_primary = true;
UPDATE number_associations SET action = 'myje ręce' WHERE number = 1 AND is_primary = true;
UPDATE number_associations SET action = 'podaje piłkę' WHERE number = 2 AND is_primary = true;
UPDATE number_associations SET action = 'skacze do przodu' WHERE number = 3 AND is_primary = true;
UPDATE number_associations SET action = 'próbuje zupę' WHERE number = 4 AND is_primary = true;
UPDATE number_associations SET action = 'dmucha bańki' WHERE number = 5 AND is_primary = true;
UPDATE number_associations SET action = 'układa kubki' WHERE number = 6 AND is_primary = true;
UPDATE number_associations SET action = 'odpala rakietę' WHERE number = 7 AND is_primary = true;
UPDATE number_associations SET action = 'kołysze się' WHERE number = 8 AND is_primary = true;
UPDATE number_associations SET action = 'odgrywa scenkę' WHERE number = 9 AND is_primary = true;
UPDATE number_associations SET action = 'myje podłogę' WHERE number = 10 AND is_primary = true;
UPDATE number_associations SET action = 'sprawdza puls' WHERE number = 11 AND is_primary = true;
UPDATE number_associations SET action = 'gra na pianinie' WHERE number = 12 AND is_primary = true;
UPDATE number_associations SET action = 'stawia wieżę' WHERE number = 13 AND is_primary = true;
UPDATE number_associations SET action = 'macha' WHERE number = 14 AND is_primary = true;
UPDATE number_associations SET action = 'balansuje na belce' WHERE number = 15 AND is_primary = true;
UPDATE number_associations SET action = 'składa papier' WHERE number = 16 AND is_primary = true;
UPDATE number_associations SET action = 'odejmuje liczby' WHERE number = 17 AND is_primary = true;
UPDATE number_associations SET action = 'jedzie na hulajnodze' WHERE number = 18 AND is_primary = true;
UPDATE number_associations SET action = 'raczkuje szybko' WHERE number = 19 AND is_primary = true;
UPDATE number_associations SET action = 'składa serwetkę' WHERE number = 20 AND is_primary = true;
UPDATE number_associations SET action = 'puszcza bączka' WHERE number = 21 AND is_primary = true;
UPDATE number_associations SET action = 'podlewa roślinę' WHERE number = 22 AND is_primary = true;
UPDATE number_associations SET action = 'koloruje obrazek' WHERE number = 23 AND is_primary = true;
UPDATE number_associations SET action = 'sortuje guziki' WHERE number = 24 AND is_primary = true;
UPDATE number_associations SET action = 'chodzi na palcach' WHERE number = 25 AND is_primary = true;
UPDATE number_associations SET action = 'podąża za mapą' WHERE number = 26 AND is_primary = true;
UPDATE number_associations SET action = 'chwyta piłkę' WHERE number = 27 AND is_primary = true;
UPDATE number_associations SET action = 'grabi liście' WHERE number = 28 AND is_primary = true;
UPDATE number_associations SET action = 'buduje zamek z piasku' WHERE number = 29 AND is_primary = true;
UPDATE number_associations SET action = 'odpowiada na zagadkę' WHERE number = 30 AND is_primary = true;
UPDATE number_associations SET action = 'pilnuje bramki' WHERE number = 31 AND is_primary = true;
UPDATE number_associations SET action = 'szczotkuje zęby' WHERE number = 32 AND is_primary = true;
UPDATE number_associations SET action = 'udaje pilota' WHERE number = 33 AND is_primary = true;
UPDATE number_associations SET action = 'miauczy delikatnie' WHERE number = 34 AND is_primary = true;
UPDATE number_associations SET action = 'dzieli przekąskę' WHERE number = 35 AND is_primary = true;
UPDATE number_associations SET action = 'turla kostkę' WHERE number = 36 AND is_primary = true;
UPDATE number_associations SET action = 'rysuje mapę' WHERE number = 37 AND is_primary = true;
UPDATE number_associations SET action = 'rzuca woreczek' WHERE number = 38 AND is_primary = true;
UPDATE number_associations SET action = 'sortuje klocki' WHERE number = 39 AND is_primary = true;
UPDATE number_associations SET action = 'dodaje liczby' WHERE number = 40 AND is_primary = true;
UPDATE number_associations SET action = 'wiąże but' WHERE number = 41 AND is_primary = true;
UPDATE number_associations SET action = 'wysyła list' WHERE number = 42 AND is_primary = true;
UPDATE number_associations SET action = 'spaceruje z psem' WHERE number = 43 AND is_primary = true;
UPDATE number_associations SET action = 'drze papier' WHERE number = 44 AND is_primary = true;
UPDATE number_associations SET action = 'skacze do tyłu' WHERE number = 45 AND is_primary = true;
UPDATE number_associations SET action = 'pije sok' WHERE number = 46 AND is_primary = true;
UPDATE number_associations SET action = 'głaszcze kota' WHERE number = 47 AND is_primary = true;
UPDATE number_associations SET action = 'mierzy wzrost' WHERE number = 48 AND is_primary = true;
UPDATE number_associations SET action = 'przebija balon' WHERE number = 49 AND is_primary = true;
UPDATE number_associations SET action = 'przesiewa piasek' WHERE number = 50 AND is_primary = true;
UPDATE number_associations SET action = 'sadzi nasionko' WHERE number = 51 AND is_primary = true;
UPDATE number_associations SET action = 'kwacze wesoło' WHERE number = 52 AND is_primary = true;
UPDATE number_associations SET action = 'wspina się po drabinie' WHERE number = 53 AND is_primary = true;
UPDATE number_associations SET action = 'pisze notatkę' WHERE number = 54 AND is_primary = true;
UPDATE number_associations SET action = 'pakuje plecak' WHERE number = 55 AND is_primary = true;
UPDATE number_associations SET action = 'naśladuje zwierzę' WHERE number = 56 AND is_primary = true;
UPDATE number_associations SET action = 'celuje z łuku' WHERE number = 57 AND is_primary = true;
UPDATE number_associations SET action = 'kopie' WHERE number = 58 AND is_primary = true;
UPDATE number_associations SET action = 'opowiada żart' WHERE number = 59 AND is_primary = true;
UPDATE number_associations SET action = 'czyta wiersz' WHERE number = 60 AND is_primary = true;
UPDATE number_associations SET action = 'śledzi gwiazdy' WHERE number = 61 AND is_primary = true;
UPDATE number_associations SET action = 'skacze przez skakankę' WHERE number = 62 AND is_primary = true;
UPDATE number_associations SET action = 'liczy koraliki' WHERE number = 63 AND is_primary = true;
UPDATE number_associations SET action = 'klęka lekko' WHERE number = 64 AND is_primary = true;
UPDATE number_associations SET action = 'kolekcjonuje liście' WHERE number = 65 AND is_primary = true;
UPDATE number_associations SET action = 'udaje nauczyciela' WHERE number = 66 AND is_primary = true;
UPDATE number_associations SET action = 'zapala lampion' WHERE number = 67 AND is_primary = true;
UPDATE number_associations SET action = 'rysuje gwiazdę' WHERE number = 68 AND is_primary = true;
UPDATE number_associations SET action = 'szczeka radośnie' WHERE number = 69 AND is_primary = true;
UPDATE number_associations SET action = 'potrząsa marakasami' WHERE number = 70 AND is_primary = true;
UPDATE number_associations SET action = 'zapina koszulę' WHERE number = 71 AND is_primary = true;
UPDATE number_associations SET action = 'dmucha w trąbkę' WHERE number = 72 AND is_primary = true;
UPDATE number_associations SET action = 'zbiera muszelki' WHERE number = 73 AND is_primary = true;
UPDATE number_associations SET action = 'sadzi kwiaty' WHERE number = 74 AND is_primary = true;
UPDATE number_associations SET action = 'rzuca piłkę' WHERE number = 75 AND is_primary = true;
UPDATE number_associations SET action = 'macha flagą' WHERE number = 76 AND is_primary = true;
UPDATE number_associations SET action = 'stawia most' WHERE number = 77 AND is_primary = true;
UPDATE number_associations SET action = 'kopie dół' WHERE number = 78 AND is_primary = true;
UPDATE number_associations SET action = 'maszeruje naprzód' WHERE number = 79 AND is_primary = true;
UPDATE number_associations SET action = 'uśmiecha się' WHERE number = 80 AND is_primary = true;
UPDATE number_associations SET action = 'zadaje pytanie' WHERE number = 81 AND is_primary = true;
UPDATE number_associations SET action = 'przeskakuje skakankę' WHERE number = 82 AND is_primary = true;
UPDATE number_associations SET action = 'karmi rybki' WHERE number = 83 AND is_primary = true;
UPDATE number_associations SET action = 'dostrzega tęczę' WHERE number = 84 AND is_primary = true;
UPDATE number_associations SET action = 'rysuje portret' WHERE number = 85 AND is_primary = true;
UPDATE number_associations SET action = 'układa puzzle' WHERE number = 86 AND is_primary = true;
UPDATE number_associations SET action = 'uderza w bęben' WHERE number = 87 AND is_primary = true;
UPDATE number_associations SET action = 'podaje herbatę' WHERE number = 88 AND is_primary = true;
UPDATE number_associations SET action = 'blokuje rzut' WHERE number = 89 AND is_primary = true;
UPDATE number_associations SET action = 'udaje lekarza' WHERE number = 90 AND is_primary = true;
UPDATE number_associations SET action = 'liczy monety' WHERE number = 91 AND is_primary = true;
UPDATE number_associations SET action = 'kręci wstążką' WHERE number = 92 AND is_primary = true;
UPDATE number_associations SET action = 'kręci bączkiem' WHERE number = 93 AND is_primary = true;
UPDATE number_associations SET action = 'wycina kształty' WHERE number = 94 AND is_primary = true;
UPDATE number_associations SET action = 'klei kształty' WHERE number = 95 AND is_primary = true;
UPDATE number_associations SET action = 'otwiera prezent' WHERE number = 96 AND is_primary = true;
UPDATE number_associations SET action = 'czyta książkę' WHERE number = 97 AND is_primary = true;
UPDATE number_associations SET action = 'pedałuje na trójkołowcu' WHERE number = 98 AND is_primary = true;
UPDATE number_associations SET action = 'udaje pirata' WHERE number = 99 AND is_primary = true;
