const obiekty = [
    "Myszka Miki",
    "Kubuś Puchatek",
    "Prosiaczek",
    "Tygrysek",
    "Kłapouchy",
    "Król Lew Simba",
    "Nala z Króla Lwa",
    "Rafiki z Króla Lwa",
    "Timon",
    "Pumba",
    "Elsa z Krainy Lodu",
    "Anna z Krainy Lodu",
    "Olaf",
    "Kristoff",
    "Sven",
    "Ariel z Małej Syrenki",
    "Sebastian z Małej Syrenki",
    "Florek (rybka z Małej Syrenki)",
    "Złotowłosa",
    "Kopciuszek",
    "Śpiąca Królewna",
    "Królewna Śnieżka",
    "Książę z Bajki",
    "Bella z Pięknej i Bestii",
    "Bestia",
    "Alicja z Krainy Czarów",
    "Cheshire Kot",
    "Biała Królowa",
    "Królowa Kier",
    "Pinokio",
    "Geppetto",
    "Dżepetto",
    "Jiminy Świerszcz",
    "Bambi",
    "Thumper (Kłapouchy królik z Bambi)",
    "Dumbo",
    "Myszka Minnie",
    "Kaczor Donald",
    "Kaczka Daisy",
    "Goofy",
    "Pluto",
    "Zygzak McQueen",
    "Złomek z Aut",
    "Buzz Astral z Toy Story",
    "Woody z Toy Story",
    "Jessie z Toy Story",
    "Rex z Toy Story",
    "Mr. Potato Head",
    "Barbie z Toy Story",
    "Forky",
    "SpongeBob Kanciastoporty",
    "Patryk Rozgwiazda",
    "Pan Krab",
    "Skalmarek",
    "Sandy Pysia",
    "Dora poznaje świat",
    "Butek (małpka Dory)",
    "Diego (kuzyn Dory)",
    "Świnka Peppa",
    "George (brat Peppy)",
    "Mama Świnka",
    "Tata Świnka",
    "Rebeka Królik",
    "Suzy Owca",
    "Marta z Marta mówi",
    "Franklin żółw",
    "Mała Mi z Muminków",
    "Muminek",
    "Panna Migotka",
    "Ryjek",
    "Włóczykij",
    "Pocahontas",
    "Mulan",
    "Vaiana (Moana)",
    "Maui z Moany",
    "Baloo z Księgi Dżungli",
    "Bagheera",
    "Mowgli",
    "Shere Khan",
    "Kung Fu Panda Po",
    "Tigress",
    "Shifu",
    "Pingwiny z Madagaskaru",
    "Król Julian",
    "Maurice",
    "Mort",
    "Minionek Bob",
    "Minionek Kevin",
    "Minionek Stuart",
    "Gru",
    "Shrek",
    "Fiona",
    "Osioł",
    "Kot w Butach",
    "Czerwony Kapturek",
    "Wilk",
    "Trzy Świnki",
    "Kłapouchy (z Kubusia Puchatka)",
    "Nemo z Gdzie jest Nemo",
    "Dory z Gdzie jest Nemo",
    "Marlin (tata Nemo)",
    "Pikachu",
    "Ash Ketchum"
  ];